global:
  scrape_interval: 5s
  external_labels:
    monitor: 'node'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.60.10:9090'] ## IP de Servidor Prometheus
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.60.10:9100','192.168.60.11:9100'] ## IP de los nodos